### ISSUE TITLE
not on list

### ISSUE THREAD

**Issue by Yevenino** [bitfocus/companion-module-analogway-livepremier#1]
Hello,,, im tryinng to find the Livepremier by analogway module, but is not on the list.
Can you help me?

**Comment by cjdenio** [comment]
Are you running Companion 1.4 or the 2.0 beta? It's possible that this module is only available in 2.0.

**Comment by Yevenino** [comment]
Im running the companion 1.4

How can i Change to BETA 2.0?

 

When i downloaded, is not option to beta 2.0….

 

Thank you for your support!

 

De: Caleb Denio [mailto:notifications@github.com] 
Enviado el: lunes, 6 de abril de 2020 10:03 a. m.
Para: bitfocus/companion-module-analogway-livepremier <companion-module-analogway-livepremier@noreply.github.com>
CC: Yevenino <nino@scancommunicacion.com>; Author <author@noreply.github.com>
Asunto: Re: [bitfocus/companion-module-analogway-livepremier] not on list (#1)

 

Are you running Companion 1.4 or the 2.0 beta? It's possible that this module is only available in 2.0.

**Comment by cjdenio** [comment]
To download the latest 2.0 build, click the tiny "**2.0 BETA**" link under the download buttons. Despite the warnings, 2.0 is quite stable, actually more so than 1.4.

![image](https://user-images.githubusercontent.com/34525547/78576563-d65a6880-77fa-11ea-93d4-c781bd299ece.png)

**Comment by Yevenino** [comment]
Perfect! Thanks!

 

De: Caleb Denio [mailto:notifications@github.com] 
Enviado el: lunes, 6 de abril de 2020 10:39 a. m.
Para: bitfocus/companion-module-analogway-livepremier <companion-module-analogway-livepremier@noreply.github.com>
CC: Yevenino <nino@scancommunicacion.com>; Author <author@noreply.github.com>
Asunto: Re: [bitfocus/companion-module-analogway-livepremier] not on list (#1)

 

To download the latest 2.0 build, click the tiny "2.0 BETA" link under the download buttons. Despite the warnings, 2.0 is quite stable, actually more so than 1.4.

 <https://user-images.githubusercontent.com/34525547/78576563-d65a6880-77fa-11ea-93d4-c781bd299ece.png>
