### ISSUE TITLE
Dante control

### ISSUE THREAD

**Issue by jmkel813** [bitfocus/companion-module-analogway-livepremier#2]
Is it possible to expand this module to control the dante source routing?

I have a client that has a need that would benefit from this capability.

**Comment by dnmeid** [comment]
So far the dante part of the Livepremier platform is only controllable via the dante ports with the common dante tools. I'm afraid dante control won't be available soon from Analog Way's side.

**Comment by istnv** [comment]
I looked into Dante control (source config would work on ANY device), their API is $15000 to license then $5000 yearly.

**Comment by jmkel813** [comment]
Not looking to control dante on the network, but I have a client that really is pushing to be able to control the internal routing (so what is feeding the specific dante outs) 

I have the command structure from Analog way to accomplish what I am needing.

I do not know if this is even capable with how Companion interfaces to the LivePremiere system

*******
Here are the control strings for manipulating the Dante routing in Aquilon.  We use a JSON protocol over a telnet connection on TCP port 10606.  The string is always followed with a HEX 04.
To set an audio source to an output:

{"op":"replace","path":"DeviceObject/audio/control/$tx/@items/<AUDIO_TRANSMITTER>/$channel/@items/<AUDIO_CHANNEL>/control/@props/source","value":”<INPUT/CHANNEL>”}\x04

 

<AUDIO_TRANSMITTER> - Values range from OUTPUT_1 to DANTE_8

<AUDIO_CHANNEL> - Values range from 1 to 8

<INPUT/CHANNEL> - Values range from INPUT_1_CHANNEL_1 to DANTE_1_CHANNEL_8

 

Example command: Route Input 1 channel 2 to Dante Group 4 channel 5

{"op":"replace","path":"DeviceObject/audio/control/$tx/@items/DANTE_4/$channel/@items/5/control/@props/source","value":”INPUT_1_CHANNEL_2”}\x04

*******

**Comment by MeestorX** [comment]
Test it using the generic TCP/UDP module. If it works, you can ask for someone to create a custom module for you.

**Comment by jmkel813** [comment]
Ill attempt that the next time I am on-site with that client and report back

Thanks

**Comment by dnmeid** [comment]
So far the LivePremier API is still work in progress. The module uses the released REST API. The JSON API is not released yet, but will be far more powerful and we definately switch to the JSON API once it'll be released and somewhat settled.

**Comment by jmkel813** [comment]
Gotcha,

So if I am understanding correctly

I should run the audio control with a generic TCP protocol for now, and then when the JSON API is realseed switch my Live premiere and the TCP to that?

Thanks guys

**Comment by dnmeid** [comment]
Analog Way updated the REST API to include audio routing capabilities, so I included it in the module.
The update is not available in Companion immediately but will be soon.

Fixed with 04a5b6a3e566f51f10615eeed65e0936e5ff097c

**Comment by dnmeid** [comment]
The build with audio routing is now available in the beta downloads. Use at least companion-2.2.0+3851
Please check it out and report back if you find any bugs (in new issue).
