### ISSUE TITLE
MODULE UPDATE REQUEST - Analog Way Live Premiere Aquilon Image Library Control

### ISSUE THREAD

**Issue by loganj2** [bitfocus/companion-module-analogway-livepremier#3]
I have been using TCP-UDP commands to reload the Image Slots form the Image Library on an Analog Way Aquilon.  The commands to change slots are - 
 
{"op":"replace","path":"DeviceObject/$still/@items/IMAGESLOT/control/@props/source","value":LIBRARYSLOT}%04
 
IMAGESLOT:  The image slot you’re changing, range is 1-48
LIBRARYSLOT:   The library slot you’re allocating to the image slot, range 1-200
 
For example, here’s the command to change the image in slot 1 to image 10 in the library:
 
{"op":"replace","path":"DeviceObject/$still/@items/1/control/@props/source","value":10}%04

This all works but it is time consuming and prone to errors.  It would be more elegant if this was incorporated into the Companion Analog Way Live Premiere module.  Hoping someone wants to tackle this - we don't have the programming skills.

Thanks!!

**Comment by dnmeid** [comment]
Hi loganj2,
the LivePremier module so far uses Analog Way's REST API. Unfortunately the REST API is not very complete and doesn't offer a command for reassigning still images to slots.
The command you have mentioned ist part of the JSON API which is not released yet and may still be subject to change. Once the JSON API is settled we will switch to it and then have much more functionality in the module.
I keep this request open to have a reminder to implement that specific command by that time.

Cheers
Dorian

**Comment by loganj2** [comment]
Hello Dorian,

I am looking forward to that release and would be very happy to test anything for your development. I appreciate the response. 

Thank you. 

Jim Logan

Logan Productions, Inc.
8035 N. Port Washington Road
Fox Point, Wisconsin  53217
 
Phone:       414-352-9691
Facsimile:  414-352-4993
 
mailto: jim@loganproductions.com 
http://www.loganproductions.com
www.globallivecast.com  Visit our NEW site for Web Broadcasting

This is a transmission from Logan Productions, Inc. and may contain information which is privileged, confidential, and protected by agreements, copyright, or contracts. If you are not the addressee, note that any disclosure, copying, distribution, or use of the contents of this message is prohibited. If you have received this transmission in error, please destroy it and notify us immediately at our toll free telephone number 1-800-823-9409.
 

On Feb 16, 2021, at 8:27 PM, dnmeid <notifications@github.com> wrote:

﻿
Hi loganj2,
the LivePremier module so far uses Analog Way's REST API. Unfortunately the REST API is not very complete and doesn't offer a command for reassigning still images to slots.
The command you have mentioned ist part of the JSON API which is not released yet and may still be subject to change. Once the JSON API is settled we will switch to it and then have much more functionality in the module.
I keep this request open to have a reminder to implement that specific command by that time.

Cheers
Dorian

**Comment by MrHurz** [comment]
Hi Dorian, do you mean the awj-protocol? If yes this is now released: https://www.analogway.com/files/uploads/produit/download/livepremier_awj_programmers_guide_v2.2.pdf

**Comment by dnmeid** [comment]
@MrHurz correct, the JSON API is now called awj.
I'm aware that it has been released and I hope I'll find the time soon to implement it with all it's glory. For sure not in june, probaby late july. Good thing is, that I'm going to do LivePremier and Midra 4k in one go.

Dorian

**Comment by ethagnawl** [comment]
> I hope I'll find the time soon to implement it with all it's glory.

This is great news. Thanks for your continued efforts on this project.

In the meantime does anyone know of any comprehensive documentation or examples for the AWJ protocol? The "programmer's guide" is ... sparse.

**Comment by Accession656** [comment]
> > I hope I'll find the time soon to implement it with all it's glory.
> 
> This is great news. Thanks for your continued efforts on this project.
> 
> In the meantime does anyone know of any comprehensive documentation or examples for the AWJ protocol? The "programmer's guide" is ... sparse.

There is a software to readout the commands. It's called "AWJ-Get" but I'm not finding it anywhere.

Is there any chance to get this Program? Do anyone know where to find it?

**Comment by dnmeid** [comment]
Good someone draws my attention again to this issue.
@loganj2
For everybody, who still doesn't know: the Companion module supporting AWJ is done and ready to use.
It is available in the release 4.2 and soon will be also working with the v3 betas.
This module supports Livepremier, Midra and Alta devices, has much more actions than the Livepremier module abs also feedbacks, variables and presets.
It also includes a Custom AWJ command to do whatever you want with the device. Just read the help of the module to get all the information.
@ethagnawl @Accession656 the AWJ module supports you with a learn button and also has can make use of the action recorder starting with v3. So you are able to get the AWJ commands from the device itself by just using it. It is more or less the same functionality of AWJ-Get, but built into the module.
The Livepremier module using the REST API will only be kept for legacy.
