### ISSUE TITLE
feature request - cut transition

### ISSUE THREAD

**Issue by philippkaiser00** [bitfocus/companion-module-analogway-livepremier#4]
Please add the cut transition for the aquilon to cut on a single screen, aux or multiple destinations. This would be a nice feature for the ascender too.

**Comment by dnmeid** [comment]
Unfortunately the REST API of LivePremier doesn't provide a cut in terms of a take while ignoring the stored transition time. If you want to use cut, you have to store your memory with a transition time of 0.0 and then take it.
It seems the REST API is not maintained a lot by Analog Way, so the chances are quite low that this will be available at any time in this module. At the moment there is a new module in development using the AWJ API, which provides also cut functionality.
