### ISSUE TITLE
REQUEST: Possibility to write text (Variables) into Layer Fields. 

### ISSUE THREAD

**Issue by 0znn** [bitfocus/companion-module-analogway-livepremier#6]
Hi There, 
Feature Request: 
its could be nice, if i could set in screen custom Variables in the field. 
Unfortunally i can only type numbers on it. 
Someone else u could like this feature?
![277767060_5571082489587983_5919861964896161250_n](https://user-images.githubusercontent.com/96270310/161780939-edc8601b-f783-472b-af5e-34d5c84538ff.jpg)

That could be nice. On the Facebook Group Someone told, that the text field is implemented by the module.

**Comment by dnmeid** [comment]
Hi, yes that sounds like a useful feature. I can implement it but I think all effort will go into the upcoming AWJ module. So you have to be a little patient.

**Comment by dnmeid** [comment]
This feature is possible with the new Analog Way AWJ module starting with Companion v3.
The AWJ module gives you several options to tackle this: 1. you can select screens and then recall to selected screens
2. you can use Custom AWJ commands to recall memories and they also support variables.
